modLoader = "javafml"
loaderVersion = "[49,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "yes_steve_model"
version = "${version}"
displayName = "Yes Steve Model"
authors = "Tianjin Accessible Care Innovation Development Co., Ltd."
description = '''

'''
logoFile = "yesstevemodel.png"

[[dependencies.yes_steve_model]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yes_steve_model]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yes_steve_model]]
modId = "architectury"
mandatory = true
versionRange = "[11,)"
ordering = "AFTER"
side = "BOTH"

